name: Deploy gantt-demo

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload project to VM (rsync)
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -az --delete --exclude='.git' --exclude='node_modules' --exclude='dist' --exclude='.github'
          path: ./
          remote_path: ${{ secrets.APP_DIR }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}

      - name: Install deps and reload PM2 on VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.APP_DIR }}
            npm ci --omit=dev
            npm run build
            if [ -f ecosystem.config.cjs ]; then
              pm2 startOrReload ecosystem.config.cjs || pm2 restart gantt-server || pm2 start server/server.js --name gantt-server
            elif [ -f ecosystem.config.js ]; then
              pm2 startOrReload ecosystem.config.js || pm2 restart gantt-server || pm2 start server/server.js --name gantt-server
            else
              pm2 restart gantt-server || pm2 start server/server.js --name gantt-server
            fi
            pm2 save

