name: Test Simple Workflow

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Echo test
        run: |
          echo "✅ Workflow is working!"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"

